apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ftch-collab
spec:
  selector:
    matchLabels:
      app: ftch-collab
      app.kubernetes.io/name: ftch-collab
      app.kubernetes.io/instance: ftch-collab
  template:
    metadata:
      labels:
        app: ftch-collab
        app.kubernetes.io/name: ftch-collab
        app.kubernetes.io/instance: ftch-collab
    spec:
      serviceAccountName: ftch-collab
      securityContext: {}
      containers:
      - name: ftch-collab
        image: "ftch-collab:6.01.0091"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 300
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 300
        envFrom:
        - secretRef:
            name: ftch-collab-aws-s3-capture-service
        - secretRef:
            name: ftch-collab-db
        - secretRef:
            name: ftch-collab-redis
        - secretRef:
            name: ftch-collab-rmq-cluster
        - configMapRef:
            name: ftch-collab-base-config
        - configMapRef:
            name: sharepoint-ftch-config
        - configMapRef:
            name: yammer-ftch-config             
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config                 
        env:
        - name: spring.application.name
          value: "ftch-collab"
        - name: application.name
          value: "ftch-collab-api"          
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: SPRING_PROFILES_INCLUDE
          value: "commercial"          
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=ftch-collab"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value
        - name: management.health.redis.enabled
          value: "true"
        - name: monitoring.tags.service
          value: "ftch-collab" 
        - name: cache.type
          value: "redis"

