apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: igwa
spec:
  selector:
    matchLabels:
      app: igwa
      app.kubernetes.io/name: igwa
      app.kubernetes.io/instance: igwa
  template:
    metadata:
      labels:
        app: igwa
        app.kubernetes.io/name: igwa
        app.kubernetes.io/instance: igwa
    spec:
      serviceAccountName: igwa
      securityContext: {}
      containers:
      - name: igwa
        image: "igwa:2.0.87"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: igwa-redis
        - configMapRef:
            name: igwa-base-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config   
        env:
        - name: spring.application.name
          value: "igwa"
        - name: SPRING_PROFILES_ACTIVE
          value: "ingestion"
        - name: SPRING_PROFILES_INCLUDE
          value: "cloud,k8,ingestion-k8"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=igwa"
        - name: monitoring.tags.service
          value: "igwa"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value           
        - name: cache.type
          value: "redis"          



