apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: expe
spec:
  selector:
    matchLabels:
      app: expe
      app.kubernetes.io/name: expe
      app.kubernetes.io/instance: expe
  template:
    metadata:
      labels:
        app: expe
        app.kubernetes.io/name: expe
        app.kubernetes.io/instance: expe
    spec:
      serviceAccountName: expe
      securityContext: {}
      containers:
      - name: expe
        image: "expe:7.01.2349"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: expe-aws-s3-archive-service
        - secretRef:
            name: expe-common-scheduler-db
        - secretRef:
            name: expe-document-db
        - secretRef:
            name: expe-rmq-cluster
        - configMapRef:
            name: expe-base-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config            
        env:    
        - name: spring.application.name
          value: "expe"
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=expe"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value          
        - name: document.db.name
          value: "workflow"    


