apiVersion: v1
kind: Service
metadata:
  name: expe
spec:
  type: ClusterIP
  selector:
    app: expe
    app.kubernetes.io/name: expe
    app.kubernetes.io/instance: expe
  ports:
    - port: 80
      targetPort: 8080
