apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: gapi
spec:
  selector:
    matchLabels:
      app: gapi
      app.kubernetes.io/name: gapi
      app.kubernetes.io/instance: gapi
  template:
    metadata:
      labels:
        app: gapi
        app.kubernetes.io/name: gapi
        app.kubernetes.io/instance: gapi
    spec:
      serviceAccountName: gapi
      securityContext: {}
      containers:
      - name: gapi
        image: "gapi:2.0.74"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: gapi-redis
        - configMapRef:
            name: gapi-base-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config   
        env:
        - name: spring.application.name
          value: "gapi"
        - name: SPRING_PROFILES_INCLUDE
          value: "cloud,k8"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=gapi"
        - name: monitoring.tags.service
          value: "gapi"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value           
        - name: cache.type
          value: "redis"          



