apiVersion: v1
kind: Service
metadata:
  name: gapi
spec:
  type: ClusterIP
  selector:
    app: gapi
    app.kubernetes.io/name: gapi
    app.kubernetes.io/instance: gapi
  ports:
    - port: 80
      targetPort: 8080
