apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: shda-chat
spec:
  selector:
    matchLabels:
      app: shda-chat
      app.kubernetes.io/name: shda-chat
      app.kubernetes.io/instance: shda-chat
  template:
    metadata:
      labels:
        app: shda-chat
        app.kubernetes.io/name: shda-chat
        app.kubernetes.io/instance: shda-chat
    spec:
      serviceAccountName: shda-chat
      securityContext: {}
      containers:
        - name: shda-chat
          image: "shda:6.1.499"
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /manage/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 180
          readinessProbe:
            httpGet:
              port: 8080
              path: /manage/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 180
          envFrom:
            - secretRef:
                name: shda-chat-db
            - secretRef:
                name: shda-chat-aws-s3-archive-service
            - secretRef:
                name: shda-chat-rmq-cluster
            - configMapRef:
                name: shda-chat-base-config
            - configMapRef:
                name: cc-shared-env-config
            - configMapRef:
                name: cc-shared-monitoring-config                   
          env:
            - name: spring.application.name
              value: "shda-chat"      
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud,k8"
            - name: SPRING_PROFILES_INCLUDE
              value: "commercial"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=shda-chat"
            - name: management.metrics.export.datadog.api-key
              valueFrom:
                secretKeyRef:
                  name: cc-datadog-api-key
                  key: value
            - name: monitoring.tags.service
              value: "shda-chat"                      