apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: uaa-secret-jwt-token
  namespace: cc-smarsh-dev
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-dev/uaa_cert

  # dest k8s secret
  destination:
    name: uaa-secret-jwt-token
    create: true

  # static secret refresh interval
  refreshAfter: 30s