apiVersion: v1
kind: Service
metadata:
  name: fiqa
spec:
  type: ClusterIP
  selector:
    app: fiqa
    app.kubernetes.io/name: fiqa
    app.kubernetes.io/instance: fiqa
  ports:
    - port: 80
      targetPort: 8080
