apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: expe-je
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: expe-je
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 45
