apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- vso.yaml
configMapGenerator:
- name: kymc-base-config
  literals:
  - kms-service-name=aws-kms-service
  - db-service-name=crypt-db
