apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prva
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prva
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 45
