apiVersion: v1
kind: Service
metadata:
  name: teamsmockserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: teamsmockserver
    app.kubernetes.io/instance: teamsmockserver
  ports:
    - port: 80
      targetPort: 8080
