apiVersion: v1
kind: Service
metadata:
  name: ftch-chat
spec:
  type: ClusterIP
  selector:
    app: ftch-chat
    app.kubernetes.io/name: ftch-chat
    app.kubernetes.io/instance: ftch-chat
  ports:
    - port: 80
      targetPort: 8080
