apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: shda-social
spec:
  selector:
    matchLabels:
      app: shda-social
      app.kubernetes.io/name: shda-social
      app.kubernetes.io/instance: shda-social
  template:
    metadata:
      labels:
        app: shda-social
        app.kubernetes.io/name: shda-social
        app.kubernetes.io/instance: shda-social
    spec:
      serviceAccountName: shda-social
      securityContext: {}
      containers:
        - name: shda-social
          image: "shda:6.01.0501"
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /manage/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 180
          readinessProbe:
            httpGet:
              port: 8080
              path: /manage/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 180
          envFrom:
            - secretRef:
               name: shda-social-db
            - secretRef:
                name: shda-social-aws-s3-archive-service
            - secretRef:
                name: shda-social-rmq
            - configMapRef:
                name: shda-social-base-config
            - configMapRef:
                name: cc-shared-env-config
            - configMapRef:
                name: cc-shared-monitoring-config                 

          env:
            - name: spring.application.name
              value: "shda-social"      
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud,k8"
            - name: SPRING_PROFILES_INCLUDE
              value: "commercial"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=shda-social"
            - name: management.metrics.export.datadog.api-key
              valueFrom:
                secretKeyRef:
                  name: cc-datadog-api-key
                  key: value
            - name: monitoring.tags.service
              value: "shda-social"   