apiVersion: v1
kind: Service
metadata:
  name: shda-social
spec:
  type: ClusterIP
  selector:
    app: shda-social
    app.kubernetes.io/name: shda-social
    app.kubernetes.io/instance: shda-social
  ports:
    - port: 80
      targetPort: 8080
