apiVersion: v1
kind: Secret
metadata:
  name: uaa-admin-client-credentials
type: Opaque
stringData:
  admin_client_credentials.yml: |
    oauth:      
      authorize:
        ssl: true
      clients:
        uaa_admin:
          authorities: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write
          authorized-grant-types: client_credentials
          override: true
          scope: ""
          secret: $cfmgmt_uaa_client_secret
        us-west-2-app-client:
          authorities: clients.read,clients.write
          authorized-grant-types: client_credentials
          override: true
          scope: ""
          secret: $uaa_app_client_secret
      user:
        authorities:
          - openid
          - scim.me
          - password.write
          - uaa.user
          - uaa.offline_token