apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
type: Opaque
stringData:
  encryption_keys.yml: |
    encryption:
      active_key_label: uaa-encryption-key-1
      encryption_keys:
      - label: uaa-encryption-key-1
        passphrase: ${encryptionkeys}