apiVersion: v1
kind: Secret
metadata:
  name: uaa-jwt-policy-signing-keys
type: Opaque
stringData:
  jwt_policy_signing_keys.yml: |
    jwt:
      token:
        refresh:
          format: opaque
        policy:
          accessTokenValiditySeconds: 43200
          activeKeyId: uaa-jwt-key-1
          global:
            accessTokenValiditySeconds: 43200
            refreshTokenValiditySeconds: 2592000
          refreshTokenValiditySeconds: 2592000        
          keys:
            uaa-jwt-key-1:
              signingKey: |
                ${jwttoken}

                                                                                                                  