apiVersion: v1
kind: Service
metadata:
  name: cc-ui
spec:
  type: ClusterIP
  selector:
    app: cc-ui
    app.kubernetes.io/name: cc-ui
    app.kubernetes.io/instance: cc-ui
  ports:
    - port: 80
      targetPort: 8080