apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: cada
spec:
  selector:
    matchLabels:
      app: cada
      app.kubernetes.io/name: cada
      app.kubernetes.io/instance: cada
  template:
    metadata:
      labels:
        app: cada
        app.kubernetes.io/name: cada
        app.kubernetes.io/instance: cada
    spec:
      serviceAccountName: cada
      securityContext: {}
      containers:
      - name: cada
        image: "cada:5.1.294"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: cada-aws-sqs-service
        - secretRef:
            name: cada-db
        - secretRef:
            name: cada-vault
        - configMapRef:
            name: cada-base-config
        - configMapRef:
            name: cada-overlays-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config               
        env:
        - name: spring.application.name
          value: "cada"      
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"   
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"          
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=cada"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value
        - name: monitoring.tags.service
          value: "cada"           



