apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: cada-base-config
  literals:
  - rds.db.service.name=cada-db
  - sqs.service.name=aws-sqs-service  
  - VAULT_SERVICE_NAME=vault
