apiVersion: v1
kind: Service
metadata:
  name: cada
spec:
  type: ClusterIP
  selector:
    app: cada
    app.kubernetes.io/name: cada
    app.kubernetes.io/instance: cada
  ports:
    - port: 80
      targetPort: 8080
