apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- encryption-key-secret.yaml
- jwt-token.yaml
- uaa-admin-secret.yaml
- uaa-app-secret.yaml
- uaa-client-secret.yaml
- uaa-db.yaml

namespace: cc-smarsh-test