apiVersion: v1
kind: Service
metadata:
  name: audi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: audi
    app.kubernetes.io/instance: audi
  ports:
    - port: 80
      targetPort: 8080
