apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tenancy.smarsh.com/cloud-provider: aws
  tenancy.smarsh.com/region: us-west-2
  tenancy.smarsh.com/service_region: nam
  tenancy.smarsh.com/customer: smarsh
  tenancy.smarsh.com/tier: test
  tenancy.smarsh.com/namespace: cc-smarsh-test
  tenancy.smarsh.com/product_family: capture
  tenancy.smarsh.com/product: cloud_capture
  tenancy.smarsh.com/deployment-identifier: aws-us-west-2-cc-smarsh-test
resources:
- ../../base
- hpa.yaml
- virtualservice.yaml
- audi-uaa.yaml
patches:
- path: deployment.yaml
images:
- name: "audi"
  newName: 593597821733.dkr.ecr.us-west-2.amazonaws.com/cc/audi
  newTag: 1.0.55
namespace: cc-smarsh-test
configMapGenerator:
- name: audi-overlays-config
  literals:
  - region=us-west-2
  - tier=test
  - uaaClientId=cc-internal-app
  - uaaUrl=https://uaa.cc-test.internal.smarsh.us-west-2.aws.smarsh.cloud
  - tokenUrl=https://uaa.cc-test.internal.smarsh.us-west-2.aws.smarsh.cloud/oauth/token
