apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tenancy.smarsh.com/cloud-provider: aws
  tenancy.smarsh.com/region: us-west-2
  tenancy.smarsh.com/service_region: nam
  tenancy.smarsh.com/customer: smarsh
  tenancy.smarsh.com/tier: perf
  tenancy.smarsh.com/namespace: cc-smarsh-perf
  tenancy.smarsh.com/product_family: capture
  tenancy.smarsh.com/product: cloud_capture
  tenancy.smarsh.com/deployment-identifier: aws-us-west-2-cc-smarsh-perf
resources:
- ../../base
- keda.yaml
- virtualservice.yaml
- prva-vso.yaml
patches:
- path: deployment.yaml
images:
- name: "prva"
  newName: 593597821733.dkr.ecr.us-west-2.amazonaws.com/cc/prva
  newTag: 6.1.1063
namespace: cc-smarsh-perf
configMapGenerator:
- name: prva-overlays-config
  literals:
  - ui.app.url=https://uaa.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud
  - application.uris=prva.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud
  - spring.task.scheduling.pool.size=10
  - provisioning.api.delete.enabled=true
  - feed.broadcast.enabled=true
  - messaging.centralAdminQueueService.environmentId=cc-sqs-uswest-perf-k8
  - environmentId=cc-sqs-uswest-perf-k8
  - instance.registration.info.instanceName= Cloud Capture uswest Perf K8 capture
    instance
  - instance.registration.info.siteId=3
  - instance.registration.info.siteName=Cloud Capture uswest Perf K8
  - instance.registration.info.queueConfigName=
  - instance.registration.info.queue=${${sqs.service.name}-sqsurl}/provisioning-instance-queue?environmentId=cc-sqs-uswest-perf-k8
