apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: cntu
spec:
  selector:
    matchLabels:
      app: cntu
      app.kubernetes.io/name: cntu
      app.kubernetes.io/instance: cntu
  template:
    metadata:
      labels:
        app: cntu
        app.kubernetes.io/name: cntu
        app.kubernetes.io/instance: cntu
    spec:
      serviceAccountName: cntu
      securityContext: {}
      containers:
      - name: cntu
        image: "cntu:5.01.0298"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: cntu-aws-s3-archive-service
        - secretRef:
            name: cntu-sftp
        - secretRef:
            name: cntu-document-db
        - secretRef:
            name: cntu-central-admin-sqs
        - configMapRef:
            name: cntu-base-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config            
        env:
        - name: spring.application.name
          value: "cntu"
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=cntu"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"           
        - name: monitoring.tags.service
          value: "cntu"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value



