apiVersion: v1
kind: Service
metadata:
  name: cntu
spec:
  type: ClusterIP
  selector:
    app: cntu
    app.kubernetes.io/name: cntu
    app.kubernetes.io/instance: cntu
  ports:
    - port: 80
      targetPort: 8080
