apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tsfa-financial-aws-s3-capture-service
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-dev/aws-s3-capture-service

  destination:
    name: tsfa-financial-aws-s3-capture-service
    create: true

  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tsfa-financial-rmq-cluster
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse
  
  path: cloud-capture/cc-dev/rmq-cluster

  destination:
    name: tsfa-financial-rmq-cluster
    create: true

  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tsfa-financial-redis
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-dev/ccredis

  destination:
    name: tsfa-financial-redis
    create: true

  refreshAfter: 30s
---  
  
  

  
