apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dnse-document-db
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-perf/document-db

  destination:
    name: dnse-document-db
    create: true

  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dnse-rmq-cluster
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-perf/rmq-cluster

  destination:
    name: dnse-rmq-cluster
    create: true

  refreshAfter: 30s
---  
