apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: tsfa-financial
spec:
  selector:
    matchLabels:
      app: tsfa-financial
      app.kubernetes.io/name: tsfa-financial
      app.kubernetes.io/instance: tsfa-financial
  template:
    metadata:
      labels:
        app: tsfa-financial
        app.kubernetes.io/name: tsfa-financial
        app.kubernetes.io/instance: tsfa-financial
    spec:
      serviceAccountName: tsfa-financial
      securityContext: {}
      containers:
      - name: tsfa-financial
        image: "tsfa-financial:1.00.1"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: tsfa-financial-aws-s3-capture-service
        - secretRef:
            name: tsfa-financial-redis
        - secretRef:
            name: tsfa-financial-rmq-cluster
        - configMapRef:
            name: tsfa-financial-base-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config                 
        env:
        - name: spring.application.name
          value: "tsfa-financial"
        - name: application.name
          value: "transformer-api-fin"
        - name:  application.id
          value: "65"
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"
        - name: SPRING_PROFILES_INCLUDE
          value: "commercial"
        - name: transformer.rmqBinder.queueName
          value: "tsfa-financial"            
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=tsfa-financial"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value
        - name: management.health.redis.enabled
          value: "true"
        - name: monitoring.tags.service
          value: "tsfa-financial"          
        - name: cache.type
          value: "redis"
