apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: crtm
spec:
  selector:
    matchLabels:
      app: crtm
      app.kubernetes.io/name: crtm
      app.kubernetes.io/instance: crtm
  template:
    metadata:
      labels:
        app: crtm
        app.kubernetes.io/name: crtm
        app.kubernetes.io/instance: crtm
    spec:
      serviceAccountName: crtm
      securityContext: {}
      containers:
      - name: crtm
        image: "crtm:6.01.0774"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: crtm-aws-s3-service
        - secretRef:
            name: crtm-aws-sqs-service
        - secretRef:
            name: crtm-vault
        - configMapRef:
            name: crtm-base-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config
        env:
        - name: spring.application.name
          value: "crtm"
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"          
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=crtm"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"           
        - name: monitoring.tags.service
          value: "crtm"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value


