apiVersion: v1
kind: Service
metadata:
  name: crtm
spec:
  type: ClusterIP
  selector:
    app: crtm
    app.kubernetes.io/name: crtm
    app.kubernetes.io/instance: crtm
  ports:
    - port: 80
      targetPort: 8080
