apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tenancy.smarsh.com/region: us-west-2
  tenancy.smarsh.com/customer: smarsh
  tenancy.smarsh.com/tier: perf
  tenancy.smarsh.com/namespace: cc-smarsh-perf
  tenancy.smarsh.com/product: cloud_capture
resources:
- ../../base
- static-secret.yaml
namespace: cc-smarsh-perf
patches:
- patch: |-
    apiVersion: opentelemetry.io/v1alpha1
    kind: OpenTelemetryCollector
    metadata:
      name: opentelemetrycollector-gateway
    spec:
      mode: deployment
      env:
      - name: HONEYCOMB_API_KEY
        valueFrom:
          secretKeyRef:
            name: honeycomb-cc
            key: value