apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: honeycomb-api-token
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/honeycomb_team_k8_perf

  # dest k8s secret
  destination:
    name: honeycomb-cc
    create: true

  # static secret refresh interval
  refreshAfter: 5m
