apiVersion: v1
kind: Service
metadata:
  name: cce-provisioning
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cce-provisioning
    app.kubernetes.io/instance: cce-provisioning
  ports:
    - port: 80
      targetPort: 8093