apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: tsfa-collab
spec:
  selector:
    matchLabels:
      app: tsfa-collab
      app.kubernetes.io/name: tsfa-collab
      app.kubernetes.io/instance: tsfa-collab
  template:
    metadata:
      labels:
        app: tsfa-collab
        app.kubernetes.io/name: tsfa-collab
        app.kubernetes.io/instance: tsfa-collab
    spec:
      serviceAccountName: tsfa-collab
      securityContext: {}
      containers:
      - name: tsfa-collab
        image: "tsfa-collab:6.1.110"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: tsfa-collab-aws-s3-capture-service
        - secretRef:
            name: tsfa-collab-redis
        - secretRef:
            name: tsfa-collab-rmq-cluster
        - configMapRef:
            name: tsfa-collab-base-config
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config                 
        env:
        - name: spring.application.name
          value: "tsfa-collab"
        - name: application.name
          value: "transformer-collab-api"
        - name:  application.id
          value: "63"             
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"
        - name: SPRING_PROFILES_INCLUDE
          value: "commercial"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: transformer.rmqBinder.queueName
          value: "tsfa-collab"            
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=tsfa-collab"
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value
        - name: management.health.redis.enabled
          value: "true"
        - name: monitoring.tags.service
          value: "tsfa-collab"          
        - name: cache.type
          value: "redis"



