apiVersion: v1
kind: Service
metadata:
  name: tsfa-collab
spec:
  type: ClusterIP
  selector:
    app: tsfa-collab
    app.kubernetes.io/name: tsfa-collab
    app.kubernetes.io/instance: tsfa-collab
  ports:
    - port: 80
      targetPort: 8080
