apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: tsfa-chat-base-config
  literals:
  - S3_SERVICE_NAME=aws-s3-capture-service
  - RMQ_CLUSTER_NAME=rmq-cluster
  - CACHE_SERVICE_NAME=ccredis
  - transformer.broker.queueName=transform-chat
  - transformer.broker.errorQueueName=transform-chat-error
  - transformer.broker.threadCount=1
