apiVersion: v1
kind: ConfigMap
metadata:
  name: sharepoint-ftch-config
data:
  sharepoint.maxRetryCount: "1"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yammer-ftch-config
data:
  yammer.token.encryption.enabled: "true"
  yammer.monitoring.service.type: opentelemetry
  yammer.content.encryption.enabled: "true"

---  