apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftch-collab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ftch-collab
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 45
