apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: uaa-secret-uaa-db
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-perf/uaa-db

  # dest k8s secret
  destination:
    name: uaa-secret-uaa-db
    create: true

  # static secret refresh interval
  refreshAfter: 30s