apiVersion: v1
kind: Service
metadata:
  name: cce-smtp
spec:
  type: ClusterIP
  ports:
  - name: tcp-smtps
    protocol: TCP
    port: 8025
    targetPort: 8080
  selector:
    app.kubernetes.io/name: cce-smtp
    app.kubernetes.io/instance: cce-smtp
