apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ftch-collab-aws-s3-capture-service
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-perf/aws-s3-capture-service

  # dest k8s secret
  destination:
    name: ftch-collab-aws-s3-capture-service
    create: true

  # static secret refresh interval
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ftch-collab-db
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-perf/fetch-db

  # dest k8s secret
  destination:
    name: ftch-collab-db
    create: true

  # static secret refresh interval
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ftch-collab-redis
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-perf/ccredis

  # dest k8s secret
  destination:
    name: ftch-collab-redis
    create: true

  # static secret refresh interval
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ftch-collab-rmq-cluster
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-perf/rmq-cluster

  # dest k8s secret
  destination:
    name: ftch-collab-rmq-cluster
    create: true

  # static secret refresh interval
  refreshAfter: 30s
---