apiVersion: v1
kind: Service
metadata:
  name: tsfa-social
spec:
  type: ClusterIP
  selector:
    app: tsfa-social
    app.kubernetes.io/name: tsfa-social
    app.kubernetes.io/instance: tsfa-social
  ports:
    - port: 80
      targetPort: 8080
