apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: wpea-base-config
  literals:
  - s3.service.name=aws-s3-capture-service
  - rabbit.cluster.name=rmq-cluster
