apiVersion: v1
kind: Service
metadata:
  name: wpea
spec:
  type: ClusterIP
  selector:
    app: wpea
    app.kubernetes.io/name: wpea
    app.kubernetes.io/instance: wpea
  ports:
    - port: 80
      targetPort: 8080
