apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: yammermockserver
spec:
  selector:
    matchLabels:
      app: yammermockserver
      app.type: mock
      app.kubernetes.io/name: yammermockserver
      app.kubernetes.io/instance: yammermockserver
  template:
    metadata:
      labels:
        app: yammermockserver
        app.type: mock
        app.kubernetes.io/name: yammermockserver
        app.kubernetes.io/instance: yammermockserver
    spec:
      serviceAccountName: yammermockserver
      securityContext: {}
      containers:
        - name: yammermockserver
          image: "yammermockserver:1.0.1"
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: yammermockserver-base-config
          env:
            - name: apiresponseURLForAll
              value: https://yammermockserver.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud/
            - name: apiresponseURLforFiles
              value: https://yammermockserver.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud/api/v1/uploaded_files/
          
 
