apiVersion: v1
kind: Service
metadata:
  name: yammermockserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yammermockserver
    app.kubernetes.io/instance: yammermockserver
  ports:
    - port: 80
      targetPort: 8443
