apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cada-aws-sqs-service
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2
  mount: concourse

  path: cloud-capture/cc-perf/aws-sqs-service
  
  destination:
    name: cada-aws-sqs-service
    create: true

  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cada-db
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-perf/cada-db

  destination:
    name: cada-db
    create: true

  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cada-vault
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-perf/vault

  destination:
    name: cada-vault
    create: true

  refreshAfter: 30s
---  
  
  
