apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tenancy.smarsh.com/cloud-provider: aws
  tenancy.smarsh.com/region: us-west-2
  tenancy.smarsh.com/service_region: nam
  tenancy.smarsh.com/customer: smarsh
  tenancy.smarsh.com/tier: perf
  tenancy.smarsh.com/namespace: cc-smarsh-perf
  tenancy.smarsh.com/product_family: capture
  tenancy.smarsh.com/product: cloud_capture
  tenancy.smarsh.com/deployment-identifier: aws-us-west-2-cc-smarsh-perf
resources:
- ../../base
- keda.yaml
- virtualservice.yaml
- cada-vso.yaml
patches:
- path: deployment.yaml
images:
- name: "cada"
  newName: 593597821733.dkr.ecr.us-west-2.amazonaws.com/cc/cada
  newTag: 6.0.397
namespace: cc-smarsh-perf
configMapGenerator:
- name: cada-overlays-config
  literals:
  - central.admin.api.site-map.ingestionURLs.2=https://gapi.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud/ingestion/{feedExternalId}
  - central.admin.api.site-map.tokenURLs.2=https://gapi.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud/token
  - environmentId=cc-sqs-uswest-perf-k8
