apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  tenancy.smarsh.com/cloud-provider: aws
  tenancy.smarsh.com/region: us-west-2
  tenancy.smarsh.com/service_region: nam
  tenancy.smarsh.com/customer: smarsh
  tenancy.smarsh.com/tier: perf
  tenancy.smarsh.com/namespace: cc-smarsh-perf
  tenancy.smarsh.com/product_family: capture
  tenancy.smarsh.com/product: cloud_capture
  tenancy.smarsh.com/deployment-identifier: aws-us-west-2-cc-smarsh-perf
resources:
  - ../../base
  - keda.yaml
  - virtualservice.yaml
  - ccui-vso.yaml
patches:
  - path: deployment.yaml
images:
  - name: "cc-ui"
    newName: 593597821733.dkr.ecr.us-west-2.amazonaws.com/cc/cc-ui
    newTag: 1.0.90
namespace: cc-smarsh-perf
configMapGenerator:
  - name: ccui-overlays-config
    literals:
      - region=us-west-2
      - tier=perf
      - uaaClientId=uaasocialappclient
      - uaaUrl=https://uaa.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud
      - tokenUrl=https://uaa.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud/oauth/token
      - prvaUrl=https://prva.cc-perf.internal.smarsh.us-west-2.aws.smarsh.cloud
