apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftch-collab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ftch-collab
      app.kubernetes.io/instance: ftch-collab
  template:
    spec:
      containers:
        - name: ftch-collab
          resources:
            limits:
              cpu: 2000m
              memory: 4G
              ephemeral-storage: 4G
            requests:
              cpu: 100m
              memory: 4G
              ephemeral-storage: 1G
          env:
          - name: logging.level.com.smarsh.spo
            value: DEBUG
