apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftch-financial
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ftch-financial
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 45