apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: "jwt-authn"
spec:
  jwtRules:
    - issuer: "issuer"
      jwksUri: "jwksuri"
      forwardOriginalToken: true

    - issuer: "issuer"
      jwksUri: "jwksuri"
      forwardOriginalToken: true