apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: rtra
spec:
  selector:
    matchLabels:
      app: rtra
      app.kubernetes.io/name: rtra
      app.kubernetes.io/instance: rtra
  template:
    metadata:
      labels:
        app: rtra
        app.kubernetes.io/name: rtra
        app.kubernetes.io/instance: rtra
    spec:
      serviceAccountName: rtra
      securityContext: {}
      containers:
      - name: rtra
        image: "rtra:6.1.1141"
        # Image that will be used to containers in the cluster
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /manage/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        readinessProbe:
          httpGet:
            port: 8080
            path: /manage/health/readiness
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 180
        envFrom:
        - secretRef:
            name: rtra-aws-s3-capture-service
        - secretRef:
            name: rtra-common-scheduler-db
        - secretRef:
            name: rtra-document-db
        - secretRef:
            name: rtra-redis
        - secretRef:
            name: rtra-rmq-cluster
        - configMapRef:
            name: rtra-base-config
        - configMapRef:
            name: rtra-overlays-config            
        - configMapRef:
            name: cc-shared-env-config
        - configMapRef:
            name: cc-shared-monitoring-config            
        env:
        - name: spring.application.name
          value: "rtra"
        - name: SPRING_PROFILES_ACTIVE
          value: "cloud,k8"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"           
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=rtra"
        - name: retrieval.api.ingestType
          value: "enrich"
        - name: monitoring.tags.service
          value: "rtra"          
        - name: management.metrics.export.datadog.api-key
          valueFrom:
            secretKeyRef:
              name: cc-datadog-api-key
              key: value  


