apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: rtra-base-config
  literals:
  - s3.service.name=aws-s3-capture-service
  - rmq.cluster.name=rmq-cluster
  - document.db.service.name=document-db
  - rds.db.service.name=quartz-db
  - cache.service.name=ccredis
  - retrieval.external.entities.binders.enabled=true
  - testUtilsController.enabled=true
  - ingestion.route.app.name=igwa


