apiVersion: v1
kind: Service
metadata:
  name: rtra
spec:
  type: NodePort
  selector:
    app: rtra
    app.kubernetes.io/name: rtra
    app.kubernetes.io/instance: rtra
  ports:
    - port: 80
      targetPort: 8080
