apiVersion: v1
kind: Service
metadata:
  name: vtglicense
spec:
  type: ClusterIP
  selector:
    app: vtglicense
    app.kubernetes.io/name: vtglicense
    app.kubernetes.io/instance: vtglicense
  ports:
    - port: 80
      targetPort: 8080
