apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: shda-financial-base-config
  literals:
  - db.service.name=scheduler-finance-db
  - s3.service.name=aws-s3-archive-service
  - rmq.cluster.name=rmq-cluster
  - scheduler.api.scheduleCallbackQueueName=financial-scheduler-callback
  - scheduler.api.tasksToRunQueueNamePrefix=financial-scheduler-
  - scheduler.api.error.queueNamePrefix=financial-scheduler-error- 
  - scheduler.jobexecution.queue=financial-execution-create-request
  - scheduler.feature.publishExecutions.type=ConcurrencyControlledRoundRobin
  - scheduler.api.jobExecutionArchiveEnabled=false
  - scheduler.api.publishJobExecutionStatisticsInDatadog=false
  - scheduler.updateRundate.endpoint.enabled=true
  - scheduler.rmq-binder.queue.fetchQueueName=financial-scheduler-fetch-main
  - scheduler.rmq-binder.queue.callbackQueueName=financial-scheduler-callback-main
  - scheduler.rmq-binder.queue.managingQueueName=financial-scheduler-managing-main
  - scheduler.rmq-binder.queueBinding.financial-scheduler-fetch=scheduler-fetch-main-out-0
  - scheduler.rmq-binder.queueBinding.financial-scheduler-callback=scheduler-callback-main-out-0
  - scheduler.rmq-binder.queueBinding.financial-scheduler-managing=scheduler-managing-main-out-0 
