apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: shda-collab-base-config
  literals:
  - db.service.name=scheduler-collab-db
  - s3.service.name=aws-s3-archive-service
  - rmq.cluster.name=rmq-cluster
  - scheduler.jobexecution.queue=collab-execution-create-request
  - scheduler.api.jobExecutionArchiveEnabled=false
  - scheduler.api.publishJobExecutionStatisticsInDatadog=false
  - scheduler.feature.publishExecutions.type=ConcurrencyControlledRoundRobin
  - scheduler.updateRundate.endpoint.enabled=true
  - scheduler.api.scheduleCallbackQueueName=collab-scheduler-callback
  - scheduler.api.tasksToRunQueueNamePrefix=collab-scheduler-
  - scheduler.api.error.queueNamePrefix=collab-scheduler-error-
