apiVersion: v1
kind: Service
metadata:
  name: shda-collab
spec:
  type: ClusterIP
  selector:
    app: shda-collab
    app.kubernetes.io/name: shda-collab
    app.kubernetes.io/instance: shda-collab
  ports:
    - port: 80
      targetPort: 8080
