apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
  - peer-auth.yaml
  - external-user-access/external-user-access-cada.yaml
  - external-user-access/external-user-access-cntu.yaml
  - external-user-access/external-user-access-prva.yaml
  - external-user-access/external-user-access-smfe.yaml
  - external-user-access/external-user-access-wpea.yaml
  - internal-user-access/internal-user-access.yaml
  - authentication/authentication-ns.yaml
  - allow-all-policy/allow-all-policy-uaa.yaml
  - allow-all-policy/allow-all-policy-cce.yaml
  - allow-all-policy/allow-all-policy-oddjob.yaml
  - allow-all-policy/allow-all-policy-vision.yaml
  - allow-all-policy/allow-all-policy-audi.yaml
  - allow-all-policy/allow-all-policy-ccui.yaml
  - external-routing/virtualservice-prva.yaml
  - external-routing/virtualservice-wpea.yaml
  - external-routing/virtualservice-smfe.yaml
  - external-routing/virtualservice-cntu.yaml
  - external-routing/virtualservice-uaa.yaml
  - external-routing/sqs-virtualservice.yaml
  - external-routing/sqs-servicentry.yaml
