apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sssmock
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sssmock
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 45
