apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: eaex-base-config
  literals:
  - s3.metadata.service.name=aws-s3-archive-service
  - rmq.cluster.name=rmq-cluster
  - eaex.db.service=document-db
  - scheduler.db.service=quartz-db
  - cache.service.name=ccredis