apiVersion: v1
kind: Service
metadata:
  name: eaex
spec:
  type: ClusterIP
  selector:
    app: eaex
    app.kubernetes.io/name: eaex
    app.kubernetes.io/instance: eaex
  ports:
  - port: 80
    targetPort: 8080
