apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: dnse-base-config
  literals:
  - rmq.cluster.name=rmq-cluster
  - document.db.service.name=document-db
