apiVersion: v1
kind: Service
metadata:
  name: zmem
spec:
  type: ClusterIP
  selector:
    app: zmem
    app.kubernetes.io/name: zmem
    app.kubernetes.io/instance: zmem
  ports:
    - port: 80
      targetPort: 8080
