apiVersion: v1
kind: ConfigMap
metadata:
  name: uaa-config
  annotations:
    kapp.k14s.io/versioned: ""
data:
  log4j2.properties: |-
    status = error

    dest = err

    name = UaaLog


    property.log_pattern=[%d{yyyy-MM-dd'T'HH:mm:ss.nnnnnn}{GMT+0}Z]
    uaa%X{context} - %pid [%t] .... %5p --- %c{1}:
    %replace{%m}{(?<=password=|client_secret=)([^&]*)}{<redacted>}%n


    appender.uaaDefaultAppender.type = Console

    appender.uaaDefaultAppender.name = UaaDefaultAppender

    appender.uaaDefaultAppender.layout.type = PatternLayout

    appender.uaaDefaultAppender.layout.pattern = [UAA] ${log_pattern}


    appender.uaaAuditAppender.type = Console

    appender.uaaAuditAppender.name = UaaAuditAppender

    appender.uaaAuditAppender.layout.type = PatternLayout

    appender.uaaAuditAppender.layout.pattern = [UAA_AUDIT] ${log_pattern}


    rootLogger.level = info

    rootLogger.appenderRef.uaaDefaultAppender.ref = UaaDefaultAppender


    logger.UAAAudit.name = UAA.Audit

    logger.UAAAudit.level = info

    logger.UAAAudit.additivity = true

    logger.UAAAudit.appenderRef.auditEventLog.ref = UaaAuditAppender


    logger.cfIdentity.name = org.cloudfoundry.identity

    logger.cfIdentity.level = info

    logger.cfIdentity.additivity = false

    logger.cfIdentity.appenderRef.uaaDefaultAppender.ref = UaaDefaultAppender
  uaa.yml: |
    issuer:
      uri: http://uaa.cc-test.internal.smarsh.us-west-2.aws.smarsh.cloud
    LOGIN_SECRET: loginsecret
    spring_profiles: postgresql
    assetBaseUrl: /resources/oss
    database:
      driverClassName: "org.postgresql.Driver"
      maxactive: 4
      maxidle: 3
      minidle: 1
      url: jdbc:postgresql://$hostname:5432/$database    

   
    zones:
      internal:
        hostnames:
          - uaa.cc-test.internal.smarsh.us-west-2.aws.smarsh.cloud
  
    smtp:
      host: null
      port: 25
      starttls: null
      from_address: null
      sslprotocols: null
      
    scim:
      user:
        override: true
      userids_enabled: true
      users:
        - admin|$cfmgmt_uaa_client_secret|admin||||uaa
