apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cntu-aws-s3-archive-service
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-dev/aws-s3-archive-service

  # dest k8s secret
  destination:
    name: cntu-aws-s3-archive-service
    create: true

  # static secret refresh interval
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cntu-central-admin-sqs
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-dev/central-admin-sqs

  # dest k8s secret
  destination:
    name: cntu-central-admin-sqs
    create: true

  # static secret refresh interval
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cntu-document-db
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-dev/document-db

  # dest k8s secret
  destination:
    name: cntu-document-db
    create: true

  # static secret refresh interval
  refreshAfter: 30s
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cntu-sftp
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  # mount path
  mount: concourse

  # path of the secret
  path: cloud-capture/cc-dev/sftp

  # dest k8s secret
  destination:
    name: cntu-sftp
    create: true

  # static secret refresh interval
  refreshAfter: 30s
