apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shda-social
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shda-social
  minReplicas: 2
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 45
