apiVersion: v1
kind: Service
metadata:
  name: spomockserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spomockserver
    app.kubernetes.io/instance: spomockserver
  ports:
    - port: 80
      targetPort: 8080
