apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: argocd
  org: Smarsh
resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: ftch-social-base-config
  literals:
  - s3.service.name=aws-s3-capture-service
  - rmq.cluster.name=rmq-cluster
  - rds.db.service.name=fetch-db
  - cache.service.name=ccredis
  - scheduler.api.worker.tasksToCompleteQueueName=social-scheduler-callback
  - scheduler.api.worker.tasksToRunQueueName=social-scheduler-fetch
  - fetch.service.executionCreateRequestQueueName=social-execution-create-request
