apiVersion: v1
kind: Service
metadata:
  name: ftch-social
spec:
  type: ClusterIP
  selector:
    app: ftch-social
    app.kubernetes.io/name: ftch-social
    app.kubernetes.io/instance: ftch-social
  ports:
    - port: 80
      targetPort: 8080
