name: Validate Kubernetes Manifests

on:
  pull_request:
    branches: [ main ]
  
jobs:
  StaticFileValidation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v14.5
        with:
          json: true
          write_output_files: true
          dir_names: "true"
          files: |
            apps/**/**/*.yaml
            apps/**/**/*.yml
            apps/**/*.yaml
            apps/**/*.yml
          files_ignore: |
            **/*.rego

      - name: Run step if any of the listed files above 
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          changedFiles: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        run: |
          . scripts/conftest/conftest_validator.sh ${{ steps.changed_files.outputs.all_changed_files }}

      - name: Run static file validation with tools KubeConform, ConfTest & Kustomize
        uses: yokawasa/action-setup-kube-tools@v0.11.0
        with:
          setup-tools: |
            kubeconform
            kustomize
            conftest
          kubeconform: '0.5.0'
          kustomize: '4.5.7'
          conftest: '0.50.0'
      - run: |
          echo "******************** Validating Dev Manifests - ${appDirPath} **********************"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-dev -o dev_consolidated_manifest.yaml
          echo -e "--------- CONSOLIDATED MANIFEST ---------- \n$(cat dev_consolidated_manifest.yaml)"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-dev
          conftest test -p apps/my-web-app/conftest/policy dev_consolidated_manifest.yaml
      - run: |
          echo "******************** Validating Test Manifests ***********************"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-test -o test_consolidated_manifest.yaml
          echo -e "--------- CONSOLIDATED MANIFEST ---------- \n$(cat test_consolidated_manifest.yaml)"
          kustomize build apps/my-web-app/overlays/aws-us-west-2-cc-smarsh-test
          conftest test -p apps/my-web-app/conftest/policy test_consolidated_manifest.yaml
