apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tsfa-collab-aws-s3-capture-service
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-test/aws-s3-capture-service

  destination:
    name: tsfa-collab-aws-s3-capture-service
    create: true

  refreshAfter: 30s

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tsfa-collab-rmq-cluster
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-test/rmq-cluster

  destination:
    name: tsfa-collab-rmq-cluster
    create: true

  refreshAfter: 30s

---  
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tsfa-collab-redis
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  type: kv-v2

  mount: concourse

  path: cloud-capture/cc-test/ccredis

  destination:
    name: tsfa-collab-redis
    create: true

  refreshAfter: 30s
---
  
